"""Add bronze.wb_www_text_search_1d & silver.wb_www_text_search_1d

Revision ID: 0baf8ec2a65d
Revises: 42c05470209e
Create Date: 2025-07-25 11:21:44.339142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0baf8ec2a65d'
down_revision: Union[str, None] = '42c05470209e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_www_text_search_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nm_position', sa.Integer(), nullable=True),
    sa.Column('app_type', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('cur', sa.String(), nullable=True),
    sa.Column('resultset', sa.String(), nullable=True),
    sa.Column('catalog_type', sa.String(), nullable=True),
    sa.Column('catalog_value', sa.String(), nullable=True),
    sa.Column('normquery', sa.String(), nullable=True),
    sa.Column('search_result_name', sa.String(), nullable=True),
    sa.Column('search_result_rmi', sa.String(), nullable=True),
    sa.Column('search_result_title', sa.String(), nullable=True),
    sa.Column('search_result_rs', sa.Integer(), nullable=True),
    sa.Column('search_result_qv', sa.String(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_time_1', sa.Integer(), nullable=True),
    sa.Column('product_time_2', sa.Integer(), nullable=True),
    sa.Column('product_wh', sa.Integer(), nullable=True),
    sa.Column('product_d_type', sa.BigInteger(), nullable=True),
    sa.Column('product_dist', sa.Integer(), nullable=True),
    sa.Column('product_root', sa.Integer(), nullable=True),
    sa.Column('product_kind_id', sa.Integer(), nullable=True),
    sa.Column('product_brand', sa.String(), nullable=True),
    sa.Column('product_brand_id', sa.Integer(), nullable=True),
    sa.Column('product_site_brand_id', sa.Integer(), nullable=True),
    sa.Column('product_colors_id', sa.Integer(), nullable=True),
    sa.Column('product_colors_name', sa.String(), nullable=True),
    sa.Column('product_subject_id', sa.Integer(), nullable=True),
    sa.Column('product_subject_parent_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_entity', sa.String(), nullable=True),
    sa.Column('product_match_id', sa.Integer(), nullable=True),
    sa.Column('product_supplier', sa.String(), nullable=True),
    sa.Column('product_supplier_id', sa.Integer(), nullable=True),
    sa.Column('product_supplier_rating', sa.Float(), nullable=True),
    sa.Column('product_supplier_flags', sa.Integer(), nullable=True),
    sa.Column('product_pics', sa.Integer(), nullable=True),
    sa.Column('product_rating', sa.Integer(), nullable=True),
    sa.Column('product_review_rating', sa.Float(), nullable=True),
    sa.Column('product_nm_review_rating', sa.Float(), nullable=True),
    sa.Column('product_feedbacks', sa.Integer(), nullable=True),
    sa.Column('product_nm_feedbacks', sa.Integer(), nullable=True),
    sa.Column('product_panel_promo_id', sa.Integer(), nullable=True),
    sa.Column('product_volume', sa.Integer(), nullable=True),
    sa.Column('product_view_flags', sa.Integer(), nullable=True),
    sa.Column('product_sizes_name', sa.String(), nullable=True),
    sa.Column('product_sizes_orig_name', sa.String(), nullable=True),
    sa.Column('product_sizes_rank', sa.Integer(), nullable=True),
    sa.Column('product_sizes_option_id', sa.Integer(), nullable=True),
    sa.Column('product_sizes_wh', sa.Integer(), nullable=True),
    sa.Column('product_sizes_time_1', sa.Integer(), nullable=True),
    sa.Column('product_sizes_time_2', sa.Integer(), nullable=True),
    sa.Column('product_sizes_d_type', sa.BigInteger(), nullable=True),
    sa.Column('product_sizes_price_basic', sa.Integer(), nullable=True),
    sa.Column('product_sizes_price_product', sa.Integer(), nullable=True),
    sa.Column('product_sizes_price_logistics', sa.Integer(), nullable=True),
    sa.Column('product_sizes_price_return', sa.Integer(), nullable=True),
    sa.Column('product_sizes_sale_conditions', sa.Integer(), nullable=True),
    sa.Column('product_sizes_payload', sa.Text(), nullable=True),
    sa.Column('product_total_quantity', sa.Integer(), nullable=True),
    sa.Column('product_log_cpm', sa.Integer(), nullable=True),
    sa.Column('product_log_promotion', sa.Integer(), nullable=True),
    sa.Column('product_log_promo_position', sa.Integer(), nullable=True),
    sa.Column('product_log_position', sa.Integer(), nullable=True),
    sa.Column('product_log_advert_id', sa.Integer(), nullable=True),
    sa.Column('product_log_tp', sa.String(), nullable=True),
    sa.Column('product_logs', sa.Text(), nullable=True),
    sa.Column('product_meta_tokens', sa.String(), nullable=True),
    sa.Column('product_meta_preset_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='silver'
    )
    op.create_table('wb_www_text_search_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_www_text_search_1d', schema='bronze')
    op.drop_table('wb_www_text_search_1d', schema='silver')
    # ### end Alembic commands ###
