"""add bronze ozon models

Revision ID: 2c42c03723ef
Revises: e64d1174c4c1
Create Date: 2025-08-21 09:18:54.065269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c42c03723ef'
down_revision: Union[str, None] = 'e64d1174c4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ozon_adv_expense_1d',
    sa.Column('response_body', postgresql.BYTEA(), nullable=False),
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('run_schedule_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('receive_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    op.create_table('ozon_analytics_data_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('run_schedule_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('receive_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    op.create_table('ozon_finance_transaction_list_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('run_schedule_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('receive_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    op.create_table('ozon_postings_create_1d',
    sa.Column('response_body', postgresql.BYTEA(), nullable=False),
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('run_schedule_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('receive_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    op.create_table('ozon_product_info_prices_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('run_schedule_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('receive_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ozon_product_info_prices_1d', schema='bronze')
    op.drop_table('ozon_postings_create_1d', schema='bronze')
    op.drop_table('ozon_finance_transaction_list_1d', schema='bronze')
    op.drop_table('ozon_analytics_data_1d', schema='bronze')
    op.drop_table('ozon_adv_expense_1d', schema='bronze')
    # ### end Alembic commands ###
