"""add btonze&silver wb_adv_promotions_1h

Revision ID: 30e4b54fe1e4
Revises: 2897b86eeaa2
Create Date: 2025-08-20 08:15:38.084593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30e4b54fe1e4'
down_revision: Union[str, None] = '2897b86eeaa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_adv_promotions_1h',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('advert_id', sa.BigInteger(), nullable=False),
    sa.Column('advert_status', sa.SmallInteger(), nullable=False),
    sa.Column('advert_type', sa.SmallInteger(), nullable=True),
    sa.Column('change_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('product_id', 'advert_id', 'business_dttm', name='pk_adv_promotions_1h'),
    schema='silver'
    )
    op.create_table('wb_adv_promotions_1h',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('run_schedule_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('receive_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('business_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_adv_promotions_1h', schema='bronze')
    op.drop_table('wb_adv_promotions_1h', schema='silver')
    # ### end Alembic commands ###
