"""initial bronze schema

Revision ID: 338884a64d90
Revises: 
Create Date: 2025-06-06 17:52:00.766649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338884a64d90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_acceptions',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_acceptions_batch_id'), 'wb_acceptions', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_acceptions_id'), 'wb_acceptions', ['id'], unique=False, schema='bronze')
    op.create_table('wb_ad_config',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_ad_config_batch_id'), 'wb_ad_config', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_ad_config_id'), 'wb_ad_config', ['id'], unique=False, schema='bronze')
    op.create_table('wb_ad_info',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_ad_info_batch_id'), 'wb_ad_info', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_ad_info_id'), 'wb_ad_info', ['id'], unique=False, schema='bronze')
    op.create_table('wb_ad_stats',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_ad_stats_batch_id'), 'wb_ad_stats', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_ad_stats_id'), 'wb_ad_stats', ['id'], unique=False, schema='bronze')
    op.create_table('wb_clusters',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_clusters_batch_id'), 'wb_clusters', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_clusters_id'), 'wb_clusters', ['id'], unique=False, schema='bronze')
    op.create_table('wb_commission',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_commission_batch_id'), 'wb_commission', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_commission_id'), 'wb_commission', ['id'], unique=False, schema='bronze')
    op.create_table('wb_keywords',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_keywords_batch_id'), 'wb_keywords', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_keywords_id'), 'wb_keywords', ['id'], unique=False, schema='bronze')
    op.create_table('wb_orders',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_orders_batch_id'), 'wb_orders', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_orders_id'), 'wb_orders', ['id'], unique=False, schema='bronze')
    op.create_table('wb_paid_storage',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_paid_storage_batch_id'), 'wb_paid_storage', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_paid_storage_id'), 'wb_paid_storage', ['id'], unique=False, schema='bronze')
    op.create_table('wb_sales',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_sales_batch_id'), 'wb_sales', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_sales_id'), 'wb_sales', ['id'], unique=False, schema='bronze')
    op.create_table('wb_sales_funnel',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_sales_funnel_batch_id'), 'wb_sales_funnel', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_sales_funnel_id'), 'wb_sales_funnel', ['id'], unique=False, schema='bronze')
    op.create_table('wb_sku_api',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_sku_api_batch_id'), 'wb_sku_api', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_sku_api_id'), 'wb_sku_api', ['id'], unique=False, schema='bronze')
    op.create_table('wb_stocks_report',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_stocks_report_batch_id'), 'wb_stocks_report', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_stocks_report_id'), 'wb_stocks_report', ['id'], unique=False, schema='bronze')
    op.create_table('wb_suppliers',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_wb_suppliers_batch_id'), 'wb_suppliers', ['batch_id'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_wb_suppliers_id'), 'wb_suppliers', ['id'], unique=False, schema='bronze')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bronze_wb_suppliers_id'), table_name='wb_suppliers', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_suppliers_batch_id'), table_name='wb_suppliers', schema='bronze')
    op.drop_table('wb_suppliers', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_stocks_report_id'), table_name='wb_stocks_report', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_stocks_report_batch_id'), table_name='wb_stocks_report', schema='bronze')
    op.drop_table('wb_stocks_report', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_sku_api_id'), table_name='wb_sku_api', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_sku_api_batch_id'), table_name='wb_sku_api', schema='bronze')
    op.drop_table('wb_sku_api', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_sales_funnel_id'), table_name='wb_sales_funnel', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_sales_funnel_batch_id'), table_name='wb_sales_funnel', schema='bronze')
    op.drop_table('wb_sales_funnel', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_sales_id'), table_name='wb_sales', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_sales_batch_id'), table_name='wb_sales', schema='bronze')
    op.drop_table('wb_sales', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_paid_storage_id'), table_name='wb_paid_storage', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_paid_storage_batch_id'), table_name='wb_paid_storage', schema='bronze')
    op.drop_table('wb_paid_storage', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_orders_id'), table_name='wb_orders', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_orders_batch_id'), table_name='wb_orders', schema='bronze')
    op.drop_table('wb_orders', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_keywords_id'), table_name='wb_keywords', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_keywords_batch_id'), table_name='wb_keywords', schema='bronze')
    op.drop_table('wb_keywords', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_commission_id'), table_name='wb_commission', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_commission_batch_id'), table_name='wb_commission', schema='bronze')
    op.drop_table('wb_commission', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_clusters_id'), table_name='wb_clusters', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_clusters_batch_id'), table_name='wb_clusters', schema='bronze')
    op.drop_table('wb_clusters', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_ad_stats_id'), table_name='wb_ad_stats', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_ad_stats_batch_id'), table_name='wb_ad_stats', schema='bronze')
    op.drop_table('wb_ad_stats', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_ad_info_id'), table_name='wb_ad_info', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_ad_info_batch_id'), table_name='wb_ad_info', schema='bronze')
    op.drop_table('wb_ad_info', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_ad_config_id'), table_name='wb_ad_config', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_ad_config_batch_id'), table_name='wb_ad_config', schema='bronze')
    op.drop_table('wb_ad_config', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_acceptions_id'), table_name='wb_acceptions', schema='bronze')
    op.drop_index(op.f('ix_bronze_wb_acceptions_batch_id'), table_name='wb_acceptions', schema='bronze')
    op.drop_table('wb_acceptions', schema='bronze')
    # ### end Alembic commands ###
