"""change finreport model

Revision ID: 35048e79cd52
Revises: 4e52cf06fabf
Create Date: 2025-07-30 14:15:21.203204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35048e79cd52'
down_revision: Union[str, None] = '4e52cf06fabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_www_fin_report_zip',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.BYTEA(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    op.drop_table('wb_www_fin_report_1d', schema='bronze')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_www_fin_report_1d',
    sa.Column('api_token_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_dttm', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('request_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_dttm', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_dttm', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], name=op.f('wb_www_fin_report_1d_api_token_id_fkey')),
    sa.PrimaryKeyConstraint('request_uuid', name=op.f('wb_www_fin_report_1d_pkey')),
    schema='bronze'
    )
    op.drop_table('wb_www_fin_report_zip', schema='bronze')
    # ### end Alembic commands ###
