"""create core schema and index for bronze.wb_clusters

Revision ID: 5415ea1e9598
Revises: 338884a64d90
Create Date: 2025-06-18 00:16:46.549996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5415ea1e9598'
down_revision: Union[str, None] = '338884a64d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mp_id'),
    schema='core'
    )
    op.create_table('sellers',
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('seller_id'),
    schema='core'
    )
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['core.sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('company_id'),
    schema='core'
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.companies.company_id'], ),
    sa.ForeignKeyConstraint(['mp_id'], ['core.marketplaces.mp_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens', schema='core')
    op.drop_table('companies', schema='core')
    op.drop_table('sellers', schema='core')
    op.drop_table('marketplaces', schema='core')
    # ### end Alembic commands ###
