"""Add silver.wb_products and wb_product_search_terms (with time_grain_enum)

Revision ID: 5a7854cc849f
Revises: 2dfc0f2c22d6
Create Date: 2025-06-23 17:20:38.473265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a7854cc849f'
down_revision: Union[str, None] = '2dfc0f2c22d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    time_grain_enum = postgresql.ENUM('hour', 'day', 'week', name='time_grain_enum')
    time_grain_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('wb_product_search_terms',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('response_uuid', sa.UUID(), nullable=False),
    sa.Column('time_grain', postgresql.ENUM('hour', 'day', 'week', name='time_grain_enum', create_type=False ), server_default='hour', nullable=False),
    sa.Column('dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('search_term', sa.Text(), nullable=False),
    sa.Column('price_min', sa.BigInteger(), nullable=True),
    sa.Column('price_max', sa.BigInteger(), nullable=True),
    sa.Column('week_frequency', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('median_position', sa.Integer(), nullable=True),
    sa.Column('avg_position', sa.Integer(), nullable=True),
    sa.Column('open_card', sa.Integer(), nullable=True),
    sa.Column('add_to_cart', sa.Integer(), nullable=True),
    sa.Column('open_to_cart', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('cart_to_order', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dttm', 'product_id', 'search_term'),
    schema='silver'
    )
    op.create_table('wb_products',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('response_uuid', sa.UUID(), nullable=False),
    sa.Column('time_grain', postgresql.ENUM('hour', 'day', 'week', name='time_grain_enum', create_type=False ), server_default='hour', nullable=False),
    sa.Column('dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_name', sa.Text(), nullable=True),
    sa.Column('brand_name', sa.Text(), nullable=True),
    sa.Column('vendor_code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_rated', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('feedback_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('dttm', 'product_id'),
    schema='silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    time_grain_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_table('wb_products', schema='silver')
    op.drop_table('wb_product_search_terms', schema='silver')
    # ### end Alembic commands ###
