"""Add bronze.wb_nm_report_detail_1d, silver.wb_buyouts_percent_1d, silver.wb_sales_funnels_1d

Revision ID: 7477b0314512
Revises: 8c1ad6776613
Create Date: 2025-07-09 15:20:00.209251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7477b0314512'
down_revision: Union[str, None] = '8c1ad6776613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_buyouts_percent_1d',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('buyouts_percent', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'date', 'nm_id', name='pk_wb_buyouts_percent_1d'),
    schema='silver'
    )
    op.create_table('wb_sales_funnels_1d',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('open_card_count', sa.Integer(), nullable=True),
    sa.Column('add_to_cart_count', sa.Integer(), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=True),
    sa.Column('orders_sum', sa.REAL(), nullable=True),
    sa.Column('buyouts_count', sa.Integer(), nullable=True),
    sa.Column('buyouts_sum', sa.Integer(), nullable=True),
    sa.Column('cancel_count', sa.Integer(), nullable=True),
    sa.Column('cancel_sum', sa.REAL(), nullable=True),
    sa.Column('avg_price', sa.REAL(), nullable=True),
    sa.Column('stocks_mp', sa.REAL(), nullable=True),
    sa.Column('stocks_wb', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'date', 'nm_id', name='pk_wb_sales_funnels_1d'),
    schema='silver'
    )
    op.create_table('wb_nm_report_detail_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_nm_report_detail_1d', schema='bronze')
    op.drop_table('wb_sales_funnels_1d', schema='silver')
    op.drop_table('wb_buyouts_percent_1d', schema='silver')
    # ### end Alembic commands ###
