"""Add tables wb_warehouse_remains_1d and wb_stocks_1d

Revision ID: 749b1c09fabc
Revises: 2c747086304c
Create Date: 2025-07-04 18:21:38.138387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '749b1c09fabc'
down_revision: Union[str, None] = '2c747086304c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_stocks_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('warehouse_name', sa.String(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('in_way_to_client', sa.Integer(), nullable=True),
    sa.Column('in_way_from_client', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'response_dttm', 'company_id', name='pk_wb_stocks_1d'),
    sa.UniqueConstraint('date', 'barcode', 'warehouse_name', name='uq_wb_stocks_1d_natural'),
    schema='silver'
    )
    op.create_table('wb_warehouse_remains_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_warehouse_remains_1d', schema='bronze')
    op.drop_table('wb_stocks_1d', schema='silver')
    # ### end Alembic commands ###
