"""Add metadata fields to bronze tables

Revision ID: 7a75bbf507ac
Revises: 5415ea1e9598
Create Date: 2025-06-18 02:41:44.448997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a75bbf507ac'
down_revision: Union[str, None] = '5415ea1e9598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_acceptions', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_acceptions', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_acceptions', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_acceptions', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_ad_config', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_ad_config', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_ad_config', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_ad_config', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_ad_info', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_ad_info', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_ad_info', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_ad_info', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_ad_stats', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_ad_stats', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_ad_stats', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_ad_stats', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_clusters', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_clusters', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_clusters', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_clusters', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_commission', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_commission', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_commission', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_commission', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_keywords', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_keywords', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_keywords', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_keywords', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_orders', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_orders', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_orders', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_orders', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_paid_storage', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_paid_storage', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_paid_storage', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_paid_storage', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_sales', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_sales', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_sales', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_sales', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_sales_funnel', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_sales_funnel', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_sales_funnel', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_sales_funnel', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_sku_api', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_sku_api', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_sku_api', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_sku_api', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_stocks_report', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_stocks_report', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_stocks_report', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_stocks_report', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    op.add_column('wb_suppliers', sa.Column('token_id', sa.Integer(), nullable=True), schema='bronze')
    op.add_column('wb_suppliers', sa.Column('response_uuid', sa.Text(), nullable=True), schema='bronze')
    op.add_column('wb_suppliers', sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True), schema='bronze')
    op.create_foreign_key(None, 'wb_suppliers', 'tokens', ['token_id'], ['token_id'], source_schema='bronze', referent_schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wb_suppliers', schema='bronze', type_='foreignkey')
    op.drop_column('wb_suppliers', 'response_dttm', schema='bronze')
    op.drop_column('wb_suppliers', 'response_uuid', schema='bronze')
    op.drop_column('wb_suppliers', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_stocks_report', schema='bronze', type_='foreignkey')
    op.drop_column('wb_stocks_report', 'response_dttm', schema='bronze')
    op.drop_column('wb_stocks_report', 'response_uuid', schema='bronze')
    op.drop_column('wb_stocks_report', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_sku_api', schema='bronze', type_='foreignkey')
    op.drop_column('wb_sku_api', 'response_dttm', schema='bronze')
    op.drop_column('wb_sku_api', 'response_uuid', schema='bronze')
    op.drop_column('wb_sku_api', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_sales_funnel', schema='bronze', type_='foreignkey')
    op.drop_column('wb_sales_funnel', 'response_dttm', schema='bronze')
    op.drop_column('wb_sales_funnel', 'response_uuid', schema='bronze')
    op.drop_column('wb_sales_funnel', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_sales', schema='bronze', type_='foreignkey')
    op.drop_column('wb_sales', 'response_dttm', schema='bronze')
    op.drop_column('wb_sales', 'response_uuid', schema='bronze')
    op.drop_column('wb_sales', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_paid_storage', schema='bronze', type_='foreignkey')
    op.drop_column('wb_paid_storage', 'response_dttm', schema='bronze')
    op.drop_column('wb_paid_storage', 'response_uuid', schema='bronze')
    op.drop_column('wb_paid_storage', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_orders', schema='bronze', type_='foreignkey')
    op.drop_column('wb_orders', 'response_dttm', schema='bronze')
    op.drop_column('wb_orders', 'response_uuid', schema='bronze')
    op.drop_column('wb_orders', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_keywords', schema='bronze', type_='foreignkey')
    op.drop_column('wb_keywords', 'response_dttm', schema='bronze')
    op.drop_column('wb_keywords', 'response_uuid', schema='bronze')
    op.drop_column('wb_keywords', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_commission', schema='bronze', type_='foreignkey')
    op.drop_column('wb_commission', 'response_dttm', schema='bronze')
    op.drop_column('wb_commission', 'response_uuid', schema='bronze')
    op.drop_column('wb_commission', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_clusters', schema='bronze', type_='foreignkey')
    op.drop_column('wb_clusters', 'response_dttm', schema='bronze')
    op.drop_column('wb_clusters', 'response_uuid', schema='bronze')
    op.drop_column('wb_clusters', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_ad_stats', schema='bronze', type_='foreignkey')
    op.drop_column('wb_ad_stats', 'response_dttm', schema='bronze')
    op.drop_column('wb_ad_stats', 'response_uuid', schema='bronze')
    op.drop_column('wb_ad_stats', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_ad_info', schema='bronze', type_='foreignkey')
    op.drop_column('wb_ad_info', 'response_dttm', schema='bronze')
    op.drop_column('wb_ad_info', 'response_uuid', schema='bronze')
    op.drop_column('wb_ad_info', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_ad_config', schema='bronze', type_='foreignkey')
    op.drop_column('wb_ad_config', 'response_dttm', schema='bronze')
    op.drop_column('wb_ad_config', 'response_uuid', schema='bronze')
    op.drop_column('wb_ad_config', 'token_id', schema='bronze')
    op.drop_constraint(None, 'wb_acceptions', schema='bronze', type_='foreignkey')
    op.drop_column('wb_acceptions', 'response_dttm', schema='bronze')
    op.drop_column('wb_acceptions', 'response_uuid', schema='bronze')
    op.drop_column('wb_acceptions', 'token_id', schema='bronze')
    # ### end Alembic commands ###
