"""Add tables wb_supplier_orders_1d and wb_order_items_1d

Revision ID: 94bca0bd9146
Revises: eaf3608a81f5
Create Date: 2025-07-03 13:56:54.114703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94bca0bd9146'
down_revision: Union[str, None] = 'eaf3608a81f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_order_items_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('g_number', sa.String(), nullable=False),
    sa.Column('sr_id', sa.String(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_change_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_type', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('oblast_okrug_name', sa.String(), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('spp', sa.Integer(), nullable=True),
    sa.Column('finished_price', sa.Float(), nullable=True),
    sa.Column('price_with_discount', sa.Float(), nullable=True),
    sa.Column('is_cancel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cancel_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sticker', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('request_uuid'),
    sa.UniqueConstraint('sr_id'),
    schema='silver'
    )
    op.create_table('wb_supplier_orders_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_supplier_orders_1d', schema='bronze')
    op.drop_table('wb_order_items_1d', schema='silver')
    # ### end Alembic commands ###
