"""add silver.wb_www_cashback_reports_1w

Revision ID: 995adc35a36c
Revises: d51c3ab3c351
Create Date: 2025-08-15 11:32:09.670145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995adc35a36c'
down_revision: Union[str, None] = 'd51c3ab3c351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_www_cashback_reports_1w',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('cashback_provided', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cashback_used', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cashback_expired', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cashback_returned', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cashback_final_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('company_id', 'request_uuid'),
    schema='silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_www_cashback_reports_1w', schema='silver')
    # ### end Alembic commands ###
