"""create silver wb_adv_product_stats and positions

Revision ID: a3a1303ce143
Revises: 763db6a17c65
Create Date: 2025-06-26 15:56:24.902581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a1303ce143'
down_revision: Union[str, None] = '763db6a17c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_adv_product_positions_1d',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('request_uuid', 'advert_id', 'nm_id', 'date'),
    schema='silver'
    )
    op.create_table('wb_adv_product_stats_1d',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('app_type', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('cpc', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('carts', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('cr', sa.Float(), nullable=False),
    sa.Column('items', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('request_uuid', 'advert_id', 'date', 'app_type', 'nm_id'),
    schema='silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_adv_product_stats_1d', schema='silver')
    op.drop_table('wb_adv_product_positions_1d', schema='silver')
    # ### end Alembic commands ###
