"""Add bronze.wb_adv_promotion_adverts_1d, silver.wb_adv_campaigns_1d, silver.wb_adv_product_rates_1d

Revision ID: b4611758b44c
Revises: afcf72575fd0
Create Date: 2025-07-08 17:31:55.217077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4611758b44c'
down_revision: Union[str, None] = 'afcf72575fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_adv_campaigns_1d',
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('run_ddtm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('create_time', sa.Text(), nullable=True),
    sa.Column('change_time', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Text(), nullable=True),
    sa.Column('daily_budget', sa.Integer(), nullable=True),
    sa.Column('search_pluse_state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('advert_id', 'request_uuid', 'run_ddtm'),
    schema='silver'
    )
    op.create_table('wb_adv_product_rates_1d',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_ddtm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('advert_status', sa.Integer(), nullable=True),
    sa.Column('advert_type', sa.Integer(), nullable=True),
    sa.Column('cpm_current', sa.Integer(), nullable=True),
    sa.Column('cpm_catalog', sa.Integer(), nullable=True),
    sa.Column('cpm_search', sa.Integer(), nullable=True),
    sa.Column('cpm_first', sa.Integer(), nullable=True),
    sa.Column('active_carousel', sa.Boolean(), nullable=True),
    sa.Column('active_recom', sa.Boolean(), nullable=True),
    sa.Column('active_booster', sa.Boolean(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('run_ddtm', 'advert_id', 'nm_id'),
    schema='silver'
    )
    op.create_table('wb_adv_promotion_adverts_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_adv_promotion_adverts_1d', schema='bronze')
    op.drop_table('wb_adv_product_rates_1d', schema='silver')
    op.drop_table('wb_adv_campaigns_1d', schema='silver')
    # ### end Alembic commands ###
