"""add silver tables for ad_campaigns and related

Revision ID: b47e1e925786
Revises: 7a75bbf507ac
Create Date: 2025-06-19 03:08:24.744434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47e1e925786'
down_revision: Union[str, None] = '7a75bbf507ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    schema='silver'
    )
    op.create_table('wb_ad_campaigns_1d',
    sa.Column('response_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('create_time', sa.Text(), nullable=True),
    sa.Column('change_time', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Text(), nullable=True),
    sa.Column('daily_budget', sa.Integer(), nullable=True),
    sa.Column('search_pluse_state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('response_uuid'),
    schema='silver'
    )
    op.create_table('wb_ad_campaigns_auto_1d',
    sa.Column('response_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.Text(), nullable=True),
    sa.Column('cpm', sa.Integer(), nullable=True),
    sa.Column('is_carousel', sa.Boolean(), nullable=True),
    sa.Column('is_recom', sa.Boolean(), nullable=True),
    sa.Column('is_booster', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('response_uuid', 'campaign_id', 'product_id'),
    schema='silver'
    )
    op.create_table('wb_ad_campaigns_products_1d',
    sa.Column('response_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_is_active', sa.Boolean(), nullable=True),
    sa.Column('subject_cpm_current', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.Text(), nullable=True),
    sa.Column('subject_is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('response_uuid', 'campaign_id', 'product_id'),
    schema='silver'
    )
    op.create_table('wb_ad_campaigns_united_1d',
    sa.Column('response_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.Text(), nullable=True),
    sa.Column('search_cpm', sa.Integer(), nullable=True),
    sa.Column('catalog_cpm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('response_uuid', 'campaign_id', 'product_id'),
    schema='silver'
    )
    op.create_table('wb_ad_keyword_clusters_5m',
    sa.Column('response_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('keyword_cluster', sa.Text(), nullable=False),
    sa.Column('keyword_cluster_views', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('response_uuid', 'campaign_id', 'keyword_cluster', 'keyword'),
    schema='silver'
    )
    op.create_table('wb_ad_stats_keywords_1d',
    sa.Column('last_response_uuid', sa.UUID(), nullable=True),
    sa.Column('last_response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.REAL(), nullable=True),
    sa.Column('cost', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'date', 'keyword'),
    schema='silver'
    )
    op.create_table('wb_ad_stats_product_position_1d',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_position', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'product_id', 'date'),
    schema='silver'
    )
    op.create_table('wb_ad_stats_products_1d',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.REAL(), nullable=True),
    sa.Column('cpc', sa.REAL(), nullable=True),
    sa.Column('cost', sa.REAL(), nullable=True),
    sa.Column('carts', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('or_', sa.REAL(), nullable=True),
    sa.Column('items', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'date', 'platform_id', 'product_id'),
    schema='silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_ad_stats_products_1d', schema='silver')
    op.drop_table('wb_ad_stats_product_position_1d', schema='silver')
    op.drop_table('wb_ad_stats_keywords_1d', schema='silver')
    op.drop_table('wb_ad_keyword_clusters_5m', schema='silver')
    op.drop_table('wb_ad_campaigns_united_1d', schema='silver')
    op.drop_table('wb_ad_campaigns_products_1d', schema='silver')
    op.drop_table('wb_ad_campaigns_auto_1d', schema='silver')
    op.drop_table('wb_ad_campaigns_1d', schema='silver')
    op.drop_table('products', schema='silver')
    # ### end Alembic commands ###
