"""Add bronze.wb_supplier_incomes_1d, silver.wb_supplies_1d

Revision ID: b9fe47428444
Revises: 7477b0314512
Create Date: 2025-07-09 16:27:20.954971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9fe47428444'
down_revision: Union[str, None] = '7477b0314512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_supplies_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.REAL(), nullable=True),
    sa.Column('date_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warehouse_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('nm_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'company_id', 'income_id', 'barcode', name='pk_wb_supplies_1d'),
    schema='silver'
    )
    op.create_table('wb_supplier_incomes_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_supplier_incomes_1d', schema='bronze')
    op.drop_table('wb_supplies_1d', schema='silver')
    # ### end Alembic commands ###
