"""add silver finreport tables

Revision ID: ccee9e0f5905
Revises: d229bca068bb
Create Date: 2025-07-30 15:57:33.870614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccee9e0f5905'
down_revision: Union[str, None] = 'd229bca068bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_compensations_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('compensation_id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('compensation_amount', sa.Float(), nullable=False),
    sa.Column('compensation_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'compensation_id'),
    schema='silver'
    )
    op.create_table('wb_fines_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fine_id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('fine_discription', sa.String(), nullable=True),
    sa.Column('fine_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('request_uuid', 'fine_id'),
    schema='silver'
    )
    op.create_table('wb_logistics_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('payment_reason', sa.String(), nullable=True),
    sa.Column('sr_id', sa.String(), nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('warehouse_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('logistics_cost', sa.Float(), nullable=False),
    sa.Column('logistic_type', sa.String(), nullable=False),
    sa.Column('delivery_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'sr_id', 'logistic_type'),
    schema='silver'
    )
    op.create_table('wb_retentions_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('retention_id', sa.String(), nullable=False),
    sa.Column('retention_amount', sa.Float(), nullable=False),
    sa.Column('retentions_discription', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'retention_id'),
    schema='silver'
    )
    op.create_table('wb_sales_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('payment_reason', sa.String(), nullable=False),
    sa.Column('sr_id', sa.String(), nullable=False),
    sa.Column('income_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nm_id', sa.Integer(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_with_discount', sa.Float(), nullable=True),
    sa.Column('wb_realization_price', sa.Float(), nullable=True),
    sa.Column('spp', sa.Float(), nullable=True),
    sa.Column('seller_payout', sa.Float(), nullable=True),
    sa.Column('commision_percent', sa.Float(), nullable=True),
    sa.Column('acquiring_amount', sa.Float(), nullable=True),
    sa.Column('acquiring_percent', sa.Float(), nullable=True),
    sa.Column('acquiring_bank', sa.String(), nullable=True),
    sa.Column('warehouse_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'sr_id', 'payment_reason'),
    schema='silver'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_sales_1d', schema='silver')
    op.drop_table('wb_retentions_1d', schema='silver')
    op.drop_table('wb_logistics_1d', schema='silver')
    op.drop_table('wb_fines_1d', schema='silver')
    op.drop_table('wb_compensations_1d', schema='silver')
    # ### end Alembic commands ###
