"""Add tables wb_cards_list_1d and wb_mp_skus_1d

Revision ID: d9e3f4e68c04
Revises: d5bd50a6d4aa
Create Date: 2025-07-04 13:35:18.183213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9e3f4e68c04'
down_revision: Union[str, None] = 'd5bd50a6d4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_mp_skus_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('imt_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('supplier_article', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('chrt_id', sa.Integer(), nullable=True),
    sa.Column('tech_size', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('request_uuid', 'response_dttm', name='pk_wb_mp_skus_1d'),
    sa.UniqueConstraint('barcode'),
    schema='silver'
    )
    op.create_table('wb_cards_list_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_cards_list_1d', schema='bronze')
    op.drop_table('wb_mp_skus_1d', schema='silver')
    # ### end Alembic commands ###
