"""Add tables wb_tariffs_commission_1d and wb_commission_1d

Revision ID: e683ae92517a
Revises: c0f53de2dad9
Create Date: 2025-07-04 00:00:08.271504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e683ae92517a'
down_revision: Union[str, None] = 'c0f53de2dad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_commission_1d',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('response_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kgvp_booking', sa.Float(), nullable=True),
    sa.Column('kgvp_marketplace', sa.Float(), nullable=True),
    sa.Column('kgvp_pick_up', sa.Float(), nullable=True),
    sa.Column('kgvp_supplier', sa.Float(), nullable=True),
    sa.Column('kgvp_supplier_express', sa.Float(), nullable=True),
    sa.Column('paid_storage_kgvp', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('request_uuid', 'date', 'subject_id'),
    schema='silver'
    )
    op.create_table('wb_tariffs_commission_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_tariffs_commission_1d', schema='bronze')
    op.drop_table('wb_commission_1d', schema='silver')
    # ### end Alembic commands ###
