"""Add tables wb_adv_auto_stat_words_1d and wb_adv_keyword_clusters_1d

Revision ID: eaf3608a81f5
Revises: 351876db2368
Create Date: 2025-06-26 23:59:41.426254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaf3608a81f5'
down_revision: Union[str, None] = '351876db2368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_adv_keyword_clusters_1d',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_dttm', sa.DateTime(timezone=True), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.Column('keyword_cluster', sa.Text(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('keyword_cluster_views', sa.Integer(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('run_dttm', 'advert_id', 'keyword_cluster', 'keyword'),
    schema='silver'
    )
    op.create_table('wb_adv_auto_stat_words_1d',
    sa.Column('api_token_id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(), nullable=False),
    sa.Column('run_dttm', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('request_dttm', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_dttm', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['core.tokens.token_id'], ),
    sa.PrimaryKeyConstraint('request_uuid'),
    schema='bronze'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wb_adv_auto_stat_words_1d', schema='bronze')
    op.drop_table('wb_adv_keyword_clusters_1d', schema='silver')
    # ### end Alembic commands ###
