"""rename or_ to cr in wb_ad_stats_products_1d

Revision ID: ee41fa451114
Revises: 2d2f429149c7
Create Date: 2025-06-19 18:39:32.910647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee41fa451114'
down_revision: Union[str, None] = '2d2f429149c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_ad_stats_products_1d', sa.Column('cr', sa.REAL(), nullable=True), schema='silver')
    op.drop_column('wb_ad_stats_products_1d', 'or_', schema='silver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wb_ad_stats_products_1d', sa.Column('or_', sa.REAL(), autoincrement=False, nullable=True), schema='silver')
    op.drop_column('wb_ad_stats_products_1d', 'cr', schema='silver')
    # ### end Alembic commands ###
